### ISSUE TITLE
Missing something in the doc/guide?

### ISSUE THREAD

**Issue by MkLHX** [bitpay/php-bitpay-light-client#24]
Hi there, 
I trying to troubleshoot something caused by non clear documentation (it's just my opinion)

What is the api key facade/config file generator?

Here on the php light lib webpage: https://bitpay.com/integrations/php-lite
On the "Initializing your BitPay light client" section
we can read :```Once you have the environment file (JSON or YML previously generated) you can initialize the client on two different ways:```

On the repo guide I can read the same thing about config file env 
https://github.com/bitpay/php-bitpay-light-client/blob/master/GUIDE.md#initializing-your-bitpay-light-client

When I click on the [Request an API token]()
![image](https://user-images.githubusercontent.com/17542841/161985094-9348b688-6af7-41d2-aace-374c00af0769.png)
I 'm redirected on https://github.com/bitpay/php-bitpay-light-client/blob/master/GUIDE.md#getting-your-client-token

https://github.com/bitpay/php-bitpay-light-client/blob/master/GUIDE.md#getting-your-client-token

On my dashboard nothing says something about "the config file generation":
![Capture d’écran 2022-04-06 152116](https://user-images.githubusercontent.com/17542841/161984347-c05a846e-bea0-4671-8924-6627871af1b1.png)

For the first time and after wasting many hours to find the good way to use it I found 
https://support.bitpay.com/hc/en-us/articles/115003001063-How-do-I-configure-and-use-the-BitPay-PHP-Library-
And in this article I can click on a link "The [BitPay Config Generator](https://github.com/bitpay/php-bitpay-client-v2/blob/master/examples/ConfigGenerator.php) 
and be redirected to :
```https://github.com/bitpay/php-bitpay-client-v2/blob/master/examples/ConfigGenerator.php```

Sorry guys but it isn't easy to understand how to get the token to request bitpay api merchant facade ...

**Comment by anbugal** [comment]
Hi @MkLHX,

We have just corrected the documentation.

If you are looking to use the Merchant Facade you should use the [Complete SDK](https://github.com/bitpay/php-bitpay-client-v2)
But if you are just looking to generate payment requests you can just use this Lite version.

Hope this helps to clarify.

**Comment by MkLHX** [comment]
Thx
