### ISSUE TITLE
Composer ext-json dependency is breaking php 7.4 package install

### ISSUE THREAD

**Issue by decrypted** [bitpay/php-bitpay-light-client#4]
Hi,

as of https://github.com/bitpay/php-bitpay-light-client/blob/master/composer.json#L17

  Problem 1
    - bitpay/sdk-light v1.1.1912 requires ext-json ^1.7 -> the requested PHP extension json has the wrong version (7.4.1) installed.
    - bitpay/sdk-light v1.0.1911 requires ext-json ^1.7 -> the requested PHP extension json has the wrong version (7.4.1) installed.
    - bitpay/sdk-light v1.0.1910.1 requires ext-json ^1.7 -> the requested PHP extension json has the wrong version (7.4.1) installed.
    - bitpay/sdk-light v1.0.1910 requires ext-json ^1.7 -> the requested PHP extension json has the wrong version (7.4.1) installed.
    - bitpay/sdk-light v1.1.1912 requires ext-json ^1.7 -> the requested PHP extension json has the wrong version (7.4.1) installed.
    - Installation request for bitpay/sdk-light ^1.0|^2.0 -> satisfiable by bitpay/sdk-light[v1.0.1910, v1.0.1910.1, v1.0.1911, v1.1.1912].

breaks the install.

Is that intentional? Some digging suggests to require ext with "*" seems the way to go.

Thx

**Comment by decrypted** [comment]
Temp workaround: --ignore-platform-reqs #herebedragons

**Comment by anbugal** [comment]
Hi @decrypted 
This is fixed in the last version [1.1.2001](https://github.com/bitpay/php-bitpay-light-client/releases/tag/v1.1.2001)

Thanks for your contribution.
