### ISSUE TITLE
Integrate Travis CI build

### ISSUE THREAD

**Issue by peter279k** [bitpay/php-bitpay-light-client#9]
To let the package tests can be tested automatically for upcoming PRs and commits, I think we should consider integrating CI builds.

It seems that the [php-bitpay-client-v2](https://github.com/bitpay/php-bitpay-client-v2) uses the Travis CI and this package can also use this.

**Comment by anbugal** [comment]
The tests on this repository are mostly functional which are not elegible for automated testing.
All changes are tested properly before being deployed.

**Comment by peter279k** [comment]
@anbugal, yes. You're right.

These tests are under for local development before deployment.
